# Use a base image with Node.js
FROM oven/bun:latest

# Set the working directory
WORKDIR /app

# Update package list and install Graphviz
RUN apt-get update && apt-get install -y graphviz && rm -rf /var/lib/apt/lists/*

# Copy dependency files
COPY package.json bun.lockb ./

# Install dependencies with Bun
RUN bun install

# Copy the rest of the app
COPY . .

# Run the app with Bun
CMD ["bun", "start"]
